name: Ontology Documentation CI

on: [push]

jobs:
 
  buildspec:
    name: Build Metanorma Standard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/cache@v3
      with:
        path: ~/.fontist
        key: fontist-ubuntu-latest
        restore-keys: fontist-ubuntu-latest

    - uses: actions-mn/setup@main
    
    - name: Run Metanorma 🔧
      run: |
         sudo apt-get update 
         sudo apt-get install asciidoctor
         sudo gem install tilt thread_safe concurrent-ruby
         sudo gem install haml -v 5.2.2
         mkdir site
         mkdir site/spec
         mkdir site/respec
         metanorma site generate --agree-to-terms -o site/spec/
         asciidoctor spec/document.adoc --trace -T spec/templates/html5/ -o site/respec/index.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         clean: false
         FOLDER: site/  
  
  
  
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: | 
         sudo apt-get update
         sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install doxygen graphviz -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode
    - name: Create Ontology Documentation 🔧
      run: |
         python3 scripts/srsbuild.py
         mkdir docs
         mv *.ttl docs/
         mv context docs/
         mv index.html docs/
         cd docs
         mkdir application
         pylode -o application/index.html application.ttl
         mv application.ttl application/
         mkdir alignments
         pylode -o alignments/index.html alignments.ttl
         mv alignments.ttl alignments/
         mkdir core
         mv index.ttl core/
         cd core
         pylode -o index.html index.ttl
         cd ..
         mkdir co
         pylode -o co/index.html co.ttl
         mv co.ttl co/
         mkdir cs
         pylode -o cs/index.html cs.ttl
         mv cs.ttl cs/
         mkdir datum
         pylode -o datum/index.html datum.ttl
         mv datum.ttl datum/
         mkdir planet
         pylode -o planet/index.html planet.ttl
         mv planet.ttl planet/
         mkdir projection
         pylode -o projection/index.html projection.ttl
         mv projection.ttl projection/
         rm objprop.ttl datatypeprop.ttl 
         mkdir examples
         cp ../examples/* examples/
         mkdir images
         cp ../images/* images/
         python3 ../scripts/htmlpostprocessing.py
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
         clean: false

  #ontdoc: 
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #  uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
  #  with: 
  #      version: v018
  #     rdffilepath: examples/epsg23032.ttl
  #      docpath: docs
  #      prefixns: http://lod.squirrel.link/data/limes/
  #     prefixnsshort: ex
  #      indexpages: true
  #      ckan: false
  #      metadatatable: true
  #      offlinecompat: false
  #      exports: cypher graphml nt n3 tlp tgf json ttl
  #      createcollections: true
  #      createnonNSPages: true
  #      createVOWL: true
  #      preferredlang: en
  #      ghpages: true
