name: Ontology Documentation CI

on: [push]

jobs:
     
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: | 
         sudo apt-get update
         sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install doxygen graphviz -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2
    - name: Create Ontology Documentation 🔧
      run: |
         python3 scripts/srsbuild.py
         mkdir docs
         mv *.ttl docs/
         cd docs
         mkdir application
         pylode -o application/index.html -i application.ttl
         mv application.ttl application/
         pylode -o index.html -i index.ttl
         mkdir co
         pylode -o co/index.html -i co.ttl
         mv co.ttl co/
         mkdir cs
         pylode -o cs/index.html -i cs.ttl
         mv cs.ttl cs/
         mkdir datum
         pylode -o datum/index.html -i datum.ttl
         mv datum.ttl datum/
         mkdir planet
         pylode -o planet/index.html -i planet.ttl
         mv planet.ttl planet/
         mkdir projection
         pylode -o projection/index.html -i projection.ttl
         mv projection.ttl projection/
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
         clean: false
