name: Ontology Documentation CI

on: [push]

jobs:
 
  buildspec:
    name: Build Metanorma Standard
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - uses: actions/cache@v3
      with:
        path: ~/.fontist
        key: fontist-ubuntu-latest
        restore-keys: fontist-ubuntu-latest

    - uses: actions-mn/setup@main
    
    - name: Run Metanorma 🔧
      run: |
         sudo apt-get update 
         sudo apt-get install asciidoctor
         sudo gem install tilt haml thread_safe concurrent-ruby
         mkdir site
         mkdir site/spec
         mkdir site/respec
         metanorma site generate --agree-to-terms -o site/spec/
         asciidoctor document/document.adoc -T document/templates/html5/ -o site/respec/index.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         BRANCH: gh-pages
         clean: false
         FOLDER: site/  
  
  
  
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: | 
         sudo apt-get update
         sudo apt-get install python3 python3-setuptools python3-pip python3-dev  -y
         sudo apt-get install gcc libpq-dev -y
         sudo apt-get install doxygen graphviz -y
         sudo apt-get install python3-venv python3-wheel -y
         sudo pip3 install wheel pylode==2.13.2
    - name: Create Ontology Documentation 🔧
      run: |
         python3 scripts/srsbuild.py
         mkdir docs
         mv *.ttl docs/
         mv index.html docs/
         cd docs
         mkdir application
         pylode -o application/index.html -i application.ttl
         mv application.ttl application/
         mkdir alignments
         pylode -o alignments/index.html -i alignments.ttl
         mv alignments.ttl alignments/
         mkdir core
         mv index.ttl core/
         cd core
         pylode -o index.html -i index.ttl
         cd ..
         mkdir co
         pylode -o co/index.html -i co.ttl
         mv co.ttl co/
         mkdir cs
         pylode -o cs/index.html -i cs.ttl
         mv cs.ttl cs/
         mkdir datum
         pylode -o datum/index.html -i datum.ttl
         mv datum.ttl datum/
         mkdir planet
         pylode -o planet/index.html -i planet.ttl
         mv planet.ttl planet/
         mkdir projection
         pylode -o projection/index.html -i projection.ttl
         mv projection.ttl projection/
         rm objprop.ttl datatypeprop.ttl 
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
         BRANCH: gh-pages
         FOLDER: docs/
         clean: false
